- task: AzureCLI@2
  displayName: Deploy Bicep via Azure CLI
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create \
        --subscription $(subscriptionId) \
        --resource-group $(resourceGroup) \
        --template-file bicep/BHF_CIR_UAT.bicep \
        --parameters \
          actionRuleName="apr-AMBA-BHF-CIR-UAT-S002" \
          targetSubscriptionId="$(subscriptionId)" \
          targetResourceGroupName="UKS-UAT-RSG-CIR02" \
          targetResourceType="microsoft.compute/virtualmachines" \
          description="AMBA Notification Assets - Suppression Alert Processing Rule" \
          enabled=true
