trigger:
- main

pool:
  name: 'default'   # self-hosted agent

variables:
  serviceConnection: bicep
  resourceGroup: rg-monitoring
  location: centralindia
  bicepFile: bicep/BHF_CIR_UAT.bicep

steps:
# 1️⃣ Clean checkout (CRITICAL for self-hosted agents)
- checkout: self
  clean: true

# 2️⃣ DEBUG – prove file exists (keep this until stable)
- script: |
    echo "Build Sources Directory:"
    echo $(Build.SourcesDirectory)
    echo "Repo contents:"
    ls -R $(Build.SourcesDirectory)
  displayName: DEBUG – list repo files

# 3️⃣ Create RG (idempotent)
- task: AzureCLI@2
  displayName: Create Resource Group (idempotent)
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create \
        --name $(resourceGroup) \
        --location $(location)

# 4️⃣ Deploy Bicep (Action Rule)
- task: AzureCLI@2
  displayName: Deploy Bicep (Action Rule)
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      cd $(Build.SourcesDirectory)

      echo "Deploying Bicep file:"
      ls bicep

      az deployment group create \
        --resource-group $(resourceGroup) \
        --template-file $(bicepFile) \
        --parameters \
          actionRuleName="apr-AMBA-BHF-CIR-UAT-S002" \
          targetResourceGroupName="TEST1" \
          targetResourceType="microsoft.compute/virtualmachines" \
          description="AMBA Notification Assets - Suppression Alert Processing Rule" \
          enabled=true
