trigger:
- main

pool:
  name: 'default'   # self-hosted agent

variables:
  serviceConnection: bicep
  resourceGroup: rg-monitoring
  location: centralindia
  bicepFile: bicep/Alert-processing-rule.bicep

steps:
# 1️⃣ Clean checkout (MANDATORY for self-hosted agents)
- checkout: self
  clean: true

# 2️⃣ Debug – prove file exists (remove later if you want)
- script: |
    echo "Sources directory:"
    echo $(Build.SourcesDirectory)
    echo "Repo contents:"
    ls -R $(Build.SourcesDirectory)
  displayName: DEBUG – verify repo contents

# 3️⃣ Create RG (idempotent)
- task: AzureCLI@2
  displayName: Create Resource Group
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create \
        --name $(resourceGroup) \
        --location $(location)

# 4️⃣ Deploy Action Rule via Bicep (NO hardcoded subscription)
- task: AzureCLI@2
  displayName: Deploy Action Rule (Bicep)
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      cd $(Build.SourcesDirectory)

      echo "Deploying Bicep file:"
      ls bicep

      az deployment group create \
        --resource-group $(resourceGroup) \
        --template-file $(bicepFile) \
        --parameters \
          actionRuleName="apr-AMBA-BHF-CIR-UAT-S002" \
          targetResourceGroupName="TEST1" \
          targetResourceType="microsoft.compute/virtualmachines" \
          actionRuleDescription="AMBA Notification Assets - Suppression Alert Processing Rule" \
          enabled=true

